
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

import java_cup.runtime.Symbol;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import Modelo.Accion;
import Modelo.Bonus;
import Modelo.CHaracterType;
import Modelo.MatchConfig;
import Modelo.ProgramaMOdelo;
import Modelo.Rule;
import Modelo.RunCommand;
import Modelo.Puntaje;
import Modelo.Estrategias;
import expr.Expresion;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class Parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public Parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public Parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\114\000\002\002\004\000\002\002\010\000\002\003" +
    "\003\000\002\003\004\000\002\014\020\000\002\014\020" +
    "\000\002\007\004\000\002\007\005\000\002\010\004\000" +
    "\002\010\005\000\002\021\006\000\002\022\006\000\002" +
    "\004\003\000\002\004\004\000\002\015\026\000\002\017" +
    "\027\000\002\020\033\000\002\011\003\000\002\011\005" +
    "\000\002\012\003\000\002\012\005\000\002\013\003\000" +
    "\002\013\005\000\002\005\003\000\002\005\004\000\002" +
    "\016\014\000\002\006\003\000\002\006\005\000\002\026" +
    "\005\000\002\026\005\000\002\026\004\000\002\026\005" +
    "\000\002\026\005\000\002\026\005\000\002\026\005\000" +
    "\002\027\003\000\002\027\003\000\002\027\003\000\002" +
    "\027\003\000\002\027\003\000\002\027\003\000\002\027" +
    "\003\000\002\027\003\000\002\027\003\000\002\027\003" +
    "\000\002\027\003\000\002\027\010\000\002\032\003\000" +
    "\002\032\003\000\002\033\003\000\002\033\003\000\002" +
    "\030\003\000\002\030\010\000\002\030\006\000\002\031" +
    "\010\000\002\034\005\000\002\035\003\000\002\035\003" +
    "\000\002\035\003\000\002\035\003\000\002\035\003\000" +
    "\002\035\003\000\002\036\003\000\002\036\003\000\002" +
    "\023\003\000\002\023\003\000\002\023\003\000\002\023" +
    "\003\000\002\023\003\000\002\024\003\000\002\024\003" +
    "\000\002\024\003\000\002\024\003\000\002\024\003\000" +
    "\002\025\003\000\002\025\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\342\000\006\004\010\005\004\001\002\000\004\076" +
    "\320\001\002\000\004\002\317\001\002\000\010\004\uffff" +
    "\005\uffff\006\uffff\001\002\000\010\004\010\005\004\006" +
    "\160\001\002\000\004\076\011\001\002\000\004\066\012" +
    "\001\002\000\004\012\013\001\002\000\004\074\014\001" +
    "\002\000\014\101\017\102\022\103\021\104\020\105\015" +
    "\001\002\000\024\013\uffbd\015\uffbd\055\uffbd\056\uffbd\063" +
    "\uffbd\064\uffbd\071\uffbd\073\uffbd\075\uffbd\001\002\000\004" +
    "\013\023\001\002\000\024\013\uffc1\015\uffc1\055\uffc1\056" +
    "\uffc1\063\uffc1\064\uffc1\071\uffc1\073\uffc1\075\uffc1\001\002" +
    "\000\024\013\uffbe\015\uffbe\055\uffbe\056\uffbe\063\uffbe\064" +
    "\uffbe\071\uffbe\073\uffbe\075\uffbe\001\002\000\024\013\uffbf" +
    "\015\uffbf\055\uffbf\056\uffbf\063\uffbf\064\uffbf\071\uffbf\073" +
    "\uffbf\075\uffbf\001\002\000\024\013\uffc0\015\uffc0\055\uffc0" +
    "\056\uffc0\063\uffc0\064\uffc0\071\uffc0\073\uffc0\075\uffc0\001" +
    "\002\000\004\074\024\001\002\000\004\070\025\001\002" +
    "\000\004\014\030\001\002\000\006\014\030\016\152\001" +
    "\002\000\004\075\151\001\002\000\070\036\063\037\042" +
    "\040\041\041\053\042\055\043\047\044\050\045\035\050" +
    "\051\051\040\052\045\053\044\054\032\065\037\072\043" +
    "\077\034\100\054\101\017\102\022\103\021\104\020\105" +
    "\015\106\036\107\065\110\056\111\052\112\062\001\002" +
    "\000\006\055\104\056\106\001\002\000\004\072\142\001" +
    "\002\000\016\015\uffce\055\uffce\056\uffce\063\uffce\064\uffce" +
    "\073\uffce\001\002\000\026\015\uffde\055\uffde\056\uffde\057" +
    "\uffde\060\uffde\061\uffde\062\uffde\063\uffde\064\uffde\073\uffde" +
    "\001\002\000\026\015\uffd5\055\uffd5\056\uffd5\057\uffd5\060" +
    "\uffd5\061\uffd5\062\uffd5\063\uffd5\064\uffd5\073\uffd5\001\002" +
    "\000\024\013\uffbc\015\uffbc\055\uffbc\056\uffbc\063\uffbc\064" +
    "\uffbc\071\uffbc\073\uffbc\075\uffbc\001\002\000\070\036\063" +
    "\037\042\040\041\041\053\042\055\043\047\044\050\045" +
    "\035\050\051\051\040\052\045\053\044\054\032\065\037" +
    "\072\043\077\034\100\054\101\017\102\022\103\021\104" +
    "\020\105\015\106\036\107\065\110\056\111\052\112\062" +
    "\001\002\000\004\072\134\001\002\000\026\015\uffda\055" +
    "\uffda\056\uffda\057\uffda\060\uffda\061\uffda\062\uffda\063\uffda" +
    "\064\uffda\073\uffda\001\002\000\026\015\uffdb\055\uffdb\056" +
    "\uffdb\057\uffdb\060\uffdb\061\uffdb\062\uffdb\063\uffdb\064\uffdb" +
    "\073\uffdb\001\002\000\070\036\063\037\042\040\041\041" +
    "\053\042\055\043\047\044\050\045\035\050\051\051\040" +
    "\052\045\053\044\054\032\065\037\072\043\077\034\100" +
    "\054\101\017\102\022\103\021\104\020\105\015\106\036" +
    "\107\065\110\056\111\052\112\062\001\002\000\004\072" +
    "\123\001\002\000\004\072\116\001\002\000\006\055\104" +
    "\056\106\001\002\000\026\015\uffd7\055\uffd7\056\uffd7\057" +
    "\uffd7\060\uffd7\061\uffd7\062\uffd7\063\uffd7\064\uffd7\073\uffd7" +
    "\001\002\000\026\015\uffd6\055\uffd6\056\uffd6\057\uffd6\060" +
    "\uffd6\061\uffd6\062\uffd6\063\uffd6\064\uffd6\073\uffd6\001\002" +
    "\000\026\015\uffd4\055\uffd4\056\uffd4\057\uffd4\060\uffd4\061" +
    "\uffd4\062\uffd4\063\uffd4\064\uffd4\073\uffd4\001\002\000\024" +
    "\013\uffb9\015\uffb9\055\uffb9\056\uffb9\063\uffb9\064\uffb9\071" +
    "\uffb9\073\uffb9\075\uffb9\001\002\000\026\015\uffd9\055\uffd9" +
    "\056\uffd9\057\uffd9\060\uffd9\061\uffd9\062\uffd9\063\uffd9\064" +
    "\uffd9\073\uffd9\001\002\000\026\015\uffdd\055\uffdd\056\uffdd" +
    "\057\uffdd\060\uffdd\061\uffdd\062\uffdd\063\uffdd\064\uffdd\073" +
    "\uffdd\001\002\000\026\015\uffd8\055\uffd8\056\uffd8\057\uffd8" +
    "\060\uffd8\061\uffd8\062\uffd8\063\uffd8\064\uffd8\073\uffd8\001" +
    "\002\000\024\013\uffba\015\uffba\055\uffba\056\uffba\063\uffba" +
    "\064\uffba\071\uffba\073\uffba\075\uffba\001\002\000\022\015" +
    "\uffb6\055\uffb6\056\uffb6\063\uffb6\064\uffb6\071\uffb6\073\uffb6" +
    "\075\uffb6\001\002\000\022\015\uffb7\055\uffb7\056\uffb7\063" +
    "\uffb7\064\uffb7\071\uffb7\073\uffb7\075\uffb7\001\002\000\010" +
    "\015\077\063\076\064\100\001\002\000\024\013\uffb8\015" +
    "\uffb8\055\uffb8\056\uffb8\063\uffb8\064\uffb8\071\uffb8\073\uffb8" +
    "\075\uffb8\001\002\000\026\015\uffdc\055\uffdc\056\uffdc\057" +
    "\uffdc\060\uffdc\061\uffdc\062\uffdc\063\uffdc\064\uffdc\073\uffdc" +
    "\001\002\000\016\055\066\056\074\057\071\060\067\061" +
    "\070\062\072\001\002\000\024\013\uffbb\015\uffbb\055\uffbb" +
    "\056\uffbb\063\uffbb\064\uffbb\071\uffbb\073\uffbb\075\uffbb\001" +
    "\002\000\032\036\uffc9\037\uffc9\040\uffc9\041\uffc9\042\uffc9" +
    "\043\uffc9\044\uffc9\045\uffc9\050\uffc9\053\uffc9\077\uffc9\100" +
    "\uffc9\001\002\000\032\036\uffc6\037\uffc6\040\uffc6\041\uffc6" +
    "\042\uffc6\043\uffc6\044\uffc6\045\uffc6\050\uffc6\053\uffc6\077" +
    "\uffc6\100\uffc6\001\002\000\032\036\uffc5\037\uffc5\040\uffc5" +
    "\041\uffc5\042\uffc5\043\uffc5\044\uffc5\045\uffc5\050\uffc5\053" +
    "\uffc5\077\uffc5\100\uffc5\001\002\000\032\036\uffc7\037\uffc7" +
    "\040\uffc7\041\uffc7\042\uffc7\043\uffc7\044\uffc7\045\uffc7\050" +
    "\uffc7\053\uffc7\077\uffc7\100\uffc7\001\002\000\032\036\uffc4" +
    "\037\uffc4\040\uffc4\041\uffc4\042\uffc4\043\uffc4\044\uffc4\045" +
    "\uffc4\050\uffc4\053\uffc4\077\uffc4\100\uffc4\001\002\000\032" +
    "\036\063\037\042\040\041\041\053\042\055\043\047\044" +
    "\050\045\035\050\051\053\044\077\034\100\054\001\002" +
    "\000\032\036\uffc8\037\uffc8\040\uffc8\041\uffc8\042\uffc8\043" +
    "\uffc8\044\uffc8\045\uffc8\050\uffc8\053\uffc8\077\uffc8\100\uffc8" +
    "\001\002\000\012\015\uffe1\063\uffe1\064\uffe1\073\uffe1\001" +
    "\002\000\070\036\063\037\042\040\041\041\053\042\055" +
    "\043\047\044\050\045\035\050\051\051\040\052\045\053" +
    "\044\054\032\065\037\072\043\077\034\100\054\101\017" +
    "\102\022\103\021\104\020\105\015\106\036\107\065\110" +
    "\056\111\052\112\062\001\002\000\014\101\017\102\022" +
    "\103\021\104\020\105\015\001\002\000\070\036\063\037" +
    "\042\040\041\041\053\042\055\043\047\044\050\045\035" +
    "\050\051\051\040\052\045\053\044\054\032\065\037\072" +
    "\043\077\034\100\054\101\017\102\022\103\021\104\020" +
    "\105\015\106\036\107\065\110\056\111\052\112\062\001" +
    "\002\000\012\015\uffe5\063\076\064\uffe5\073\uffe5\001\002" +
    "\000\004\075\ufff7\001\002\000\012\015\uffe4\063\uffe4\064" +
    "\uffe4\073\uffe4\001\002\000\034\051\uffc3\052\uffc3\070\uffc3" +
    "\101\uffc3\102\uffc3\103\uffc3\104\uffc3\105\uffc3\106\uffc3\107" +
    "\uffc3\110\uffc3\111\uffc3\112\uffc3\001\002\000\004\070\110" +
    "\001\002\000\034\051\uffc2\052\uffc2\070\uffc2\101\uffc2\102" +
    "\uffc2\103\uffc2\104\uffc2\105\uffc2\106\uffc2\107\uffc2\110\uffc2" +
    "\111\uffc2\112\uffc2\001\002\000\012\015\uffdf\063\uffdf\064" +
    "\uffdf\073\uffdf\001\002\000\026\101\017\102\022\103\021" +
    "\104\020\105\015\106\036\107\065\110\056\111\052\112" +
    "\062\001\002\000\006\071\114\075\113\001\002\000\006" +
    "\071\uffec\075\uffec\001\002\000\026\101\017\102\022\103" +
    "\021\104\020\105\015\106\036\107\065\110\056\111\052" +
    "\112\062\001\002\000\012\015\uffca\063\uffca\064\uffca\073" +
    "\uffca\001\002\000\006\071\uffeb\075\uffeb\001\002\000\006" +
    "\046\117\047\121\001\002\000\006\073\uffd2\075\uffd2\001" +
    "\002\000\004\073\122\001\002\000\006\073\uffd1\075\uffd1" +
    "\001\002\000\016\015\uffcc\055\uffcc\056\uffcc\063\uffcc\064" +
    "\uffcc\073\uffcc\001\002\000\010\046\117\047\121\054\032" +
    "\001\002\000\004\075\uffd0\001\002\000\004\075\uffcf\001" +
    "\002\000\004\075\127\001\002\000\026\101\017\102\022" +
    "\103\021\104\020\105\015\106\036\107\065\110\056\111" +
    "\052\112\062\001\002\000\004\073\131\001\002\000\026" +
    "\015\uffd3\055\uffd3\056\uffd3\057\uffd3\060\uffd3\061\uffd3\062" +
    "\uffd3\063\uffd3\064\uffd3\073\uffd3\001\002\000\010\063\076" +
    "\064\100\073\133\001\002\000\012\015\uffe2\063\uffe2\064" +
    "\uffe2\073\uffe2\001\002\000\006\046\117\047\121\001\002" +
    "\000\004\075\136\001\002\000\004\077\137\001\002\000" +
    "\004\073\140\001\002\000\016\015\uffcd\055\uffcd\056\uffcd" +
    "\063\uffcd\064\uffcd\073\uffcd\001\002\000\012\015\uffe3\063" +
    "\uffe3\064\uffe3\073\uffe3\001\002\000\006\046\117\047\121" +
    "\001\002\000\004\075\144\001\002\000\004\077\145\001" +
    "\002\000\004\073\146\001\002\000\010\055\uffcb\056\uffcb" +
    "\075\uffcb\001\002\000\032\051\040\052\045\101\017\102" +
    "\022\103\021\104\020\105\015\106\036\107\065\110\056" +
    "\111\052\112\062\001\002\000\012\015\uffe0\063\uffe0\064" +
    "\uffe0\073\uffe0\001\002\000\006\014\ufffb\016\ufffb\001\002" +
    "\000\014\101\017\102\022\103\021\104\020\105\015\001" +
    "\002\000\004\075\154\001\002\000\006\014\ufffa\016\ufffa" +
    "\001\002\000\004\071\156\001\002\000\004\067\157\001" +
    "\002\000\010\004\ufffd\005\ufffd\006\ufffd\001\002\000\004" +
    "\076\210\001\002\000\006\006\ufff5\007\ufff5\001\002\000" +
    "\006\006\160\007\165\001\002\000\010\004\ufffe\005\ufffe" +
    "\006\ufffe\001\002\000\006\006\ufff4\007\ufff4\001\002\000" +
    "\004\066\166\001\002\000\004\010\167\001\002\000\004" +
    "\070\174\001\002\000\006\010\uffea\067\uffea\001\002\000" +
    "\006\010\167\067\173\001\002\000\006\010\uffe9\067\uffe9" +
    "\001\002\000\004\002\000\001\002\000\004\076\175\001" +
    "\002\000\006\071\uffe7\075\uffe7\001\002\000\006\071\200" +
    "\075\177\001\002\000\004\076\207\001\002\000\004\011" +
    "\201\001\002\000\004\066\202\001\002\000\004\023\203" +
    "\001\002\000\004\074\204\001\002\000\004\077\205\001" +
    "\002\000\004\067\206\001\002\000\006\010\uffe8\067\uffe8" +
    "\001\002\000\006\071\uffe6\075\uffe6\001\002\000\004\066" +
    "\211\001\002\000\004\017\212\001\002\000\004\074\213" +
    "\001\002\000\004\070\214\001\002\000\004\076\215\001" +
    "\002\000\004\075\216\001\002\000\004\076\217\001\002" +
    "\000\004\071\220\001\002\000\004\020\221\001\002\000" +
    "\004\074\222\001\002\000\004\077\223\001\002\000\004" +
    "\021\224\001\002\000\004\074\225\001\002\000\004\066" +
    "\226\001\002\000\004\024\273\001\002\000\004\022\230" +
    "\001\002\000\004\074\231\001\002\000\004\066\232\001" +
    "\002\000\004\031\235\001\002\000\004\067\234\001\002" +
    "\000\006\006\ufff3\007\ufff3\001\002\000\004\074\236\001" +
    "\002\000\004\070\237\001\002\000\014\101\017\102\022" +
    "\103\021\104\020\105\015\001\002\000\006\071\ufff0\075" +
    "\ufff0\001\002\000\006\071\243\075\242\001\002\000\014" +
    "\101\017\102\022\103\021\104\020\105\015\001\002\000" +
    "\004\075\244\001\002\000\004\032\245\001\002\000\004" +
    "\074\246\001\002\000\004\077\247\001\002\000\004\075" +
    "\250\001\002\000\004\033\251\001\002\000\004\074\252" +
    "\001\002\000\004\070\253\001\002\000\014\106\036\107" +
    "\065\110\056\111\052\112\062\001\002\000\006\071\uffee" +
    "\075\uffee\001\002\000\006\071\257\075\256\001\002\000" +
    "\014\106\036\107\065\110\056\111\052\112\062\001\002" +
    "\000\004\075\260\001\002\000\004\034\261\001\002\000" +
    "\004\074\262\001\002\000\004\077\263\001\002\000\004" +
    "\075\264\001\002\000\004\035\265\001\002\000\004\074" +
    "\266\001\002\000\004\077\267\001\002\000\004\067\270" +
    "\001\002\000\004\067\ufff1\001\002\000\006\071\uffed\075" +
    "\uffed\001\002\000\006\071\uffef\075\uffef\001\002\000\004" +
    "\074\274\001\002\000\004\077\275\001\002\000\004\075" +
    "\276\001\002\000\004\025\277\001\002\000\004\074\300" +
    "\001\002\000\004\077\301\001\002\000\004\075\302\001" +
    "\002\000\004\026\303\001\002\000\004\074\304\001\002" +
    "\000\004\077\305\001\002\000\004\075\306\001\002\000" +
    "\004\027\307\001\002\000\004\074\310\001\002\000\004" +
    "\077\311\001\002\000\004\075\312\001\002\000\004\030" +
    "\313\001\002\000\004\074\314\001\002\000\004\077\315" +
    "\001\002\000\004\067\316\001\002\000\004\022\ufff2\001" +
    "\002\000\004\002\001\001\002\000\004\066\321\001\002" +
    "\000\004\012\322\001\002\000\004\074\323\001\002\000" +
    "\014\106\036\107\065\110\056\111\052\112\062\001\002" +
    "\000\004\013\325\001\002\000\004\074\326\001\002\000" +
    "\004\070\327\001\002\000\004\014\332\001\002\000\006" +
    "\014\332\016\337\001\002\000\004\075\336\001\002\000" +
    "\070\036\063\037\042\040\041\041\053\042\055\043\047" +
    "\044\050\045\035\050\051\051\040\052\045\053\044\054" +
    "\032\065\037\072\043\077\034\100\054\101\017\102\022" +
    "\103\021\104\020\105\015\106\036\107\065\110\056\111" +
    "\052\112\062\001\002\000\010\015\334\063\076\064\100" +
    "\001\002\000\014\106\036\107\065\110\056\111\052\112" +
    "\062\001\002\000\004\075\ufff6\001\002\000\006\014\ufff9" +
    "\016\ufff9\001\002\000\014\106\036\107\065\110\056\111" +
    "\052\112\062\001\002\000\004\075\341\001\002\000\006" +
    "\014\ufff8\016\ufff8\001\002\000\004\071\343\001\002\000" +
    "\004\067\344\001\002\000\010\004\ufffc\005\ufffc\006\ufffc" +
    "\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\342\000\010\002\004\003\006\014\005\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\010" +
    "\004\161\014\162\015\160\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\023\015\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\006\007" +
    "\025\021\026\001\001\000\004\021\152\001\001\000\002" +
    "\001\001\000\020\023\057\024\056\025\032\026\060\027" +
    "\063\030\030\031\045\001\001\000\004\036\146\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\020\023\057\024\056" +
    "\025\032\026\140\027\063\030\030\031\045\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\020" +
    "\023\057\024\056\025\032\026\131\027\063\030\030\031" +
    "\045\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\036\104\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\035\072\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\027\074\001" +
    "\001\000\002\001\001\000\002\001\001\000\020\023\057" +
    "\024\056\025\032\026\102\027\063\030\030\031\045\001" +
    "\001\000\004\023\101\001\001\000\020\023\057\024\056" +
    "\025\032\026\100\027\063\030\030\031\045\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\034\106\001\001\000\002\001\001\000" +
    "\002\001\001\000\012\013\110\023\057\024\056\025\111" +
    "\001\001\000\002\001\001\000\002\001\001\000\010\023" +
    "\057\024\056\025\114\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\032\117\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\010" +
    "\031\124\032\123\033\125\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\010\023\057\024\056" +
    "\025\127\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\032\134\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\032\142\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\012\023\057\024\056\025\032\030\147" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\023" +
    "\154\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\015\163\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\006\005" +
    "\170\016\167\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\016\171\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\006\175\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\017\226\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\020\232\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\006\011\240\023\237\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\023\271\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\006\012\254\024\253\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\024\270" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\024\323\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\006\010\327\022" +
    "\330\001\001\000\004\022\337\001\001\000\002\001\001" +
    "\000\020\023\057\024\056\025\032\026\332\027\063\030" +
    "\030\031\045\001\001\000\002\001\001\000\004\024\334" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\024" +
    "\341\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}




    private ProgramaMOdelo program;
    private final List<CompileError> errors = new ArrayList<>();

    public ProgramaMOdelo getProgram() {
        return program;
    }

    public List<CompileError> getErrors() {
        return errors;
    }

    @Override
    public void syntax_error(Symbol current) {

        int line = current == null ? 0 : current.left + 1;
        int column = current == null ? 0 : current.right + 1;

        String value = "EOF";

        if (current != null && current.value != null) {
            value = current.value.toString();
        }

        errors.add(new CompileError(
            "Sintáctico",
            "Token inesperado: " + value,
            line,
            column
        ));

        throw new ParseAbortException();
    }

    @Override
    public void unrecovered_syntax_error(Symbol current) throws Exception {
        syntax_error(current);
    }



/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$Parser$actions {
  private final Parser parser;

  /** Constructor */
  CUP$Parser$actions(Parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action_part00000000(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Parser$result;

      /* select the action based on the action number */
      switch (CUP$Parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= program EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		ProgramaMOdelo start_val = (ProgramaMOdelo)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		RESULT = start_val;
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Parser$parser.done_parsing();
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // program ::= strategy_list match_list MAIN LBRACE run_list RBRACE 
            {
              ProgramaMOdelo RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).right;
		ArrayList s = (ArrayList)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-5)).value;
		int mleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).left;
		int mright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).right;
		ArrayList m = (ArrayList)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-4)).value;
		int rleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int rright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		ArrayList r = (ArrayList)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
        ProgramaMOdelo result = new ProgramaMOdelo(s, m, r);
        program = result;
        RESULT = result;
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("program",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // strategy_list ::= strategy 
            {
              ArrayList RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Estrategias s = (Estrategias)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
        ArrayList list = new ArrayList();
        list.add(s);
        RESULT = list;
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("strategy_list",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // strategy_list ::= strategy_list strategy 
            {
              ArrayList RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		ArrayList l = (ArrayList)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Estrategias s = (Estrategias)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
        l.add(s);
        RESULT = l;
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("strategy_list",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // strategy ::= MAGE ID LBRACE INITIAL COLON mage_action RULES COLON LBRACKET mage_rule_list ELSE mage_action RBRACKET RBRACE 
            {
              Estrategias RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-12)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-12)).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-12)).value;
		int ileft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-8)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-8)).right;
		Accion i = (Accion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-8)).value;
		int rleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).left;
		int rright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).right;
		ArrayList r = (ArrayList)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-4)).value;
		int dleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int dright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Accion d = (Accion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		
        RESULT = new Estrategias(
            n,
            CHaracterType.MAGE,
            i,
            r,
            d
        );
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("strategy",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-13)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // strategy ::= WARRIOR ID LBRACE INITIAL COLON warrior_action RULES COLON LBRACKET warrior_rule_list ELSE warrior_action RBRACKET RBRACE 
            {
              Estrategias RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-12)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-12)).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-12)).value;
		int ileft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-8)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-8)).right;
		Accion i = (Accion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-8)).value;
		int rleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).left;
		int rright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).right;
		ArrayList r = (ArrayList)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-4)).value;
		int dleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int dright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Accion d = (Accion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		
        RESULT = new Estrategias(
            n,
            CHaracterType.WARRIOR,
            i,
            r,
            d
        );
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("strategy",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-13)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // mage_rule_list ::= mage_rule COMMA 
            {
              ArrayList RESULT =null;
		int rleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int rright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Rule r = (Rule)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
        ArrayList list = new ArrayList();
        list.add(r);
        RESULT = list;
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("mage_rule_list",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // mage_rule_list ::= mage_rule_list mage_rule COMMA 
            {
              ArrayList RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		ArrayList l = (ArrayList)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int rleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int rright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Rule r = (Rule)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
        l.add(r);
        RESULT = l;
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("mage_rule_list",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // warrior_rule_list ::= warrior_rule COMMA 
            {
              ArrayList RESULT =null;
		int rleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int rright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Rule r = (Rule)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
        ArrayList list = new ArrayList();
        list.add(r);
        RESULT = list;
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("warrior_rule_list",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // warrior_rule_list ::= warrior_rule_list warrior_rule COMMA 
            {
              ArrayList RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		ArrayList l = (ArrayList)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int rleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int rright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Rule r = (Rule)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
        l.add(r);
        RESULT = l;
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("warrior_rule_list",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // mage_rule ::= IF condition THEN mage_action 
            {
              Rule RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Expresion c = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Accion a = (Accion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
        RESULT = new Rule(c, a);
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("mage_rule",15, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // warrior_rule ::= IF condition THEN warrior_action 
            {
              Rule RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Expresion c = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Accion a = (Accion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
        RESULT = new Rule(c, a);
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("warrior_rule",16, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // match_list ::= match_def 
            {
              ArrayList RESULT =null;
		int mleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int mright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		MatchConfig m = (MatchConfig)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
        ArrayList list = new ArrayList();
        list.add(m);
        RESULT = list;
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("match_list",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // match_list ::= match_list match_def 
            {
              ArrayList RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		ArrayList l = (ArrayList)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int mleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int mright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		MatchConfig m = (MatchConfig)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
        l.add(m);
        RESULT = l;
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("match_list",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // match_def ::= MATCH ID LBRACE PLAYERS COLON LBRACKET ID COMMA ID RBRACKET ROUNDS COLON INT SCORING COLON scoring BONUSES COLON bonuses RBRACE 
            {
              MatchConfig RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-18)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-18)).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-18)).value;
		int p1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-13)).left;
		int p1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-13)).right;
		String p1 = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-13)).value;
		int p2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-11)).left;
		int p2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-11)).right;
		String p2 = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-11)).value;
		int rleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)).left;
		int rright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)).right;
		Integer r = (Integer)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-7)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).right;
		Puntaje s = (Puntaje)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-4)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Bonus b = (Bonus)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
        RESULT = new MatchConfig(
            n,
            p1,
            p2,
            r,
            s,
            b
        );
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("match_def",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-19)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // scoring ::= LBRACE DAMAGE_POINT COLON INT COMMA HEALING_POINT COLON INT COMMA SUCCESSFUL_DEFENSE COLON INT COMMA VICTORY_BONUS COLON INT COMMA FAILED_ACTION_PENALTY COLON INT RBRACE 
            {
              Puntaje RESULT =null;
		int dleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-17)).left;
		int dright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-17)).right;
		Integer d = (Integer)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-17)).value;
		int hleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-13)).left;
		int hright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-13)).right;
		Integer h = (Integer)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-13)).value;
		int sdleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-9)).left;
		int sdright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-9)).right;
		Integer sd = (Integer)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-9)).value;
		int vleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).right;
		Integer v = (Integer)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-5)).value;
		int fleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int fright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Integer f = (Integer)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
        RESULT = new Puntaje(
            d,
            h,
            sd,
            v,
            f
        );
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("scoring",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-20)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // bonuses ::= LBRACE MAGE_COMBO COLON LBRACKET mage_action_values RBRACKET COMMA MAGE_COMBO_POINTS COLON INT COMMA WARRIOR_COMBO COLON LBRACKET warrior_action_values RBRACKET COMMA WARRIOR_COMBO_POINTS COLON INT COMMA LOW_HEALTH_VICTORY COLON INT RBRACE 
            {
              Bonus RESULT =null;
		int mcleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-20)).left;
		int mcright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-20)).right;
		ArrayList mc = (ArrayList)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-20)).value;
		int mcpleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-15)).left;
		int mcpright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-15)).right;
		Integer mcp = (Integer)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-15)).value;
		int wcleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-10)).left;
		int wcright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-10)).right;
		ArrayList wc = (ArrayList)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-10)).value;
		int wcpleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).left;
		int wcpright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).right;
		Integer wcp = (Integer)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-5)).value;
		int lhvleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int lhvright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Integer lhv = (Integer)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
        RESULT = new Bonus(
            mc,
            mcp,
            wc,
            wcp,
            lhv
        );
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("bonuses",14, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-24)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // mage_action_values ::= mage_action 
            {
              ArrayList RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Accion a = (Accion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
        ArrayList list = new ArrayList();
        list.add(a);
        RESULT = list;
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("mage_action_values",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // mage_action_values ::= mage_action_values COMMA mage_action 
            {
              ArrayList RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		ArrayList l = (ArrayList)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Accion a = (Accion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
        l.add(a);
        RESULT = l;
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("mage_action_values",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // warrior_action_values ::= warrior_action 
            {
              ArrayList RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Accion a = (Accion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
        ArrayList list = new ArrayList();
        list.add(a);
        RESULT = list;
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("warrior_action_values",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // warrior_action_values ::= warrior_action_values COMMA warrior_action 
            {
              ArrayList RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		ArrayList l = (ArrayList)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Accion a = (Accion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
        l.add(a);
        RESULT = l;
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("warrior_action_values",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // any_action_values ::= any_action 
            {
              ArrayList RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Accion a = (Accion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
        ArrayList list = new ArrayList();
        list.add(a);
        RESULT = list;
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("any_action_values",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // any_action_values ::= any_action_values COMMA any_action 
            {
              ArrayList RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		ArrayList l = (ArrayList)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Accion a = (Accion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
        l.add(a);
        RESULT = l;
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("any_action_values",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // run_list ::= run_def 
            {
              ArrayList RESULT =null;
		int rleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int rright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		RunCommand r = (RunCommand)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
        ArrayList list = new ArrayList();
        list.add(r);
        RESULT = list;
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("run_list",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // run_list ::= run_list run_def 
            {
              ArrayList RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		ArrayList l = (ArrayList)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int rleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int rright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		RunCommand r = (RunCommand)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
        l.add(r);
        RESULT = l;
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("run_list",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // run_def ::= RUN LBRACKET id_list RBRACKET WITH LBRACE SEED COLON INT RBRACE 
            {
              RunCommand RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)).right;
		ArrayList l = (ArrayList)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-7)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Integer s = (Integer)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
        RESULT = new RunCommand(l, s);
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("run_def",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-9)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // id_list ::= ID 
            {
              ArrayList RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
        ArrayList list = new ArrayList();
        list.add(i);
        RESULT = list;
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("id_list",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // id_list ::= id_list COMMA ID 
            {
              ArrayList RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		ArrayList l = (ArrayList)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int ileft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
        l.add(i);
        RESULT = l;
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("id_list",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // condition ::= condition OR condition 
            {
              Expr RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Expr a = (Expr)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expr b = (Expr)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
        RESULT = new Expr.Binary("||", a, b);
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condition",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // condition ::= condition AND condition 
            {
              Expresion RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Expresion a = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expresion b = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
        RESULT = new Expr.Binary("&&", a, b);
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condition",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // condition ::= NOT condition 
            {
              Expresion RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expresion c = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
        RESULT = new Expr.Not(c);
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condition",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // condition ::= LPAREN condition RPAREN 
            {
              Expresion RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Expresion c = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
        RESULT = c;
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condition",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // condition ::= numeric_expr comparison_operator numeric_expr 
            {
              Expresion RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Expresion a = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int oleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int oright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String o = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expresion b = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
        RESULT = new Expr.Binary(o, a, b);
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condition",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // condition ::= action_expr equality_operator action_expr 
            {
              Expresion RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Expresion a = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int oleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int oright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String o = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expresion b = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
        RESULT = new Expr.Binary(o, a, b);
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condition",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // condition ::= list_expr equality_operator action_list_expr 
            {
              Expresion RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Expresion a = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int oleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int oright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String o = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expresion b = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
        RESULT = new Expr.Binary(o, a, b);
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condition",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // numeric_expr ::= INT 
            {
              Expresion RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Integer i = (Integer)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
        RESULT = new Expr.Literal(i);
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("numeric_expr",21, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // numeric_expr ::= FLOAT 
            {
              Expresion RESULT =null;
		int fleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int fright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Double f = (Double)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
        RESULT = new Expr.Literal(f);
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("numeric_expr",21, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // numeric_expr ::= ROUND_NUMBER 
            {
              Expresion RESULT =null;
		
        RESULT = new Expr.Variable("round_number");
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("numeric_expr",21, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // numeric_expr ::= TOTAL_ROUNDS 
            {
              Expresion RESULT =null;
		
        RESULT = new Expr.Variable("total_rounds");
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("numeric_expr",21, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // numeric_expr ::= SELF_HEALTH 
            {
              Expresion RESULT =null;
		
        RESULT = new Expr.Variable("self_health");
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("numeric_expr",21, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // numeric_expr ::= OPPONENT_HEALTH 
            {
              Expresion RESULT =null;
		
        RESULT = new Expr.Variable("opponent_health");
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("numeric_expr",21, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // numeric_expr ::= SELF_RESOURCE 
            {
              Expresion RESULT =null;
		
        RESULT = new Expr.Variable("self_resource");
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("numeric_expr",21, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // numeric_expr ::= OPPONENT_RESOURCE 
            {
              Expresion RESULT =null;
		
        RESULT = new Expr.Variable("opponent_resource");
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("numeric_expr",21, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // numeric_expr ::= SELF_SCORE 
            {
              Expresion RESULT =null;
		
        RESULT = new Expr.Variable("self_score");
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("numeric_expr",21, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // numeric_expr ::= OPPONENT_SCORE 
            {
              Expresion RESULT =null;
		
        RESULT = new Expr.Variable("opponent_score");
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("numeric_expr",21, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // numeric_expr ::= RANDOM 
            {
              Expresion RESULT =null;
		
        RESULT = new Expr.Variable("random");
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("numeric_expr",21, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // numeric_expr ::= GET_MOVES_COUNT LPAREN history_source COMMA any_action RPAREN 
            {
              Expresion RESULT =null;
		int hleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int hright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		Expresion h = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Accion a = (Accion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
        RESULT = new Expresion.Function(
            "get_moves_count",
            Arrays.asList(
                h,
                new Expresion.Literal(a)
            )
        );
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("numeric_expr",21, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // history_expr ::= SELF_HISTORY 
            {
              Expresion RESULT =null;
		
        RESULT = new Expr.Variable("self_history");
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("history_expr",24, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // history_expr ::= OPPONENT_HISTORY 
            {
              Expresion RESULT =null;
		
        RESULT = new Expr.Variable("opponent_history");
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("history_expr",24, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // history_source ::= history_expr 
            {
              Expresion RESULT =null;
		int hleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int hright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expresion h = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
        RESULT = h;
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("history_source",25, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // history_source ::= list_expr 
            {
              Expresion RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expresion l = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
        RESULT = l;
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("history_source",25, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // action_expr ::= any_action 
            {
              Expresion RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Accion a = (Accion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
        RESULT = new Expr.Literal(a);
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("action_expr",22, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // action_expr ::= GET_MOVE LPAREN history_expr COMMA INT RPAREN 
            {
              Expresion RESULT =null;
		int hleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int hright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		Expresion h = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int ileft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Integer i = (Integer)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
        RESULT = new Expr.Function(
            "get_move",
            Arrays.asList(
                h,
                new Expr.Literal(i)
            )
        );
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("action_expr",22, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // action_expr ::= LAST_MOVE LPAREN history_expr RPAREN 
            {
              Expresion RESULT =null;
		int hleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int hright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Expresion h = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
        RESULT = new Expr.Function(
            "last_move",
            Arrays.asList(h)
        );
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("action_expr",22, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // list_expr ::= GET_LAST_N_MOVES LPAREN history_expr COMMA INT RPAREN 
            {
              Expresion RESULT =null;
		int hleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int hright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		Expresion h = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int ileft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Integer i = (Integer)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
        RESULT = new Expr.Function(
            "get_last_n_moves",
            Arrays.asList(
                h,
                new Expr.Literal(i)
            )
        );
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("list_expr",23, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // action_list_expr ::= LBRACKET any_action_values RBRACKET 
            {
              Expresion RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		ArrayList l = (ArrayList)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
        RESULT = new Expr.Literal(l);
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("action_list_expr",26, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // comparison_operator ::= EQ 
            {
              String RESULT =null;
		
        RESULT = "==";
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("comparison_operator",27, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // comparison_operator ::= NEQ 
            {
              String RESULT =null;
		
        RESULT = "!=";
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("comparison_operator",27, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // comparison_operator ::= GT 
            {
              String RESULT =null;
		
        RESULT = ">";
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("comparison_operator",27, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // comparison_operator ::= LT 
            {
              String RESULT =null;
		
        RESULT = "<";
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("comparison_operator",27, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // comparison_operator ::= GTE 
            {
              String RESULT =null;
		
        RESULT = ">=";
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("comparison_operator",27, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // comparison_operator ::= LTE 
            {
              String RESULT =null;
		
        RESULT = "<=";
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("comparison_operator",27, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // equality_operator ::= EQ 
            {
              String RESULT =null;
		
        RESULT = "==";
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("equality_operator",28, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // equality_operator ::= NEQ 
            {
              String RESULT =null;
		
        RESULT = "!=";
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("equality_operator",28, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // mage_action ::= ARCANE_BOLT 
            {
              Accion RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Accion a = (Accion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
        RESULT = a;
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("mage_action",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // mage_action ::= FIREBALL 
            {
              Accion RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Accion a = (Accion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
        RESULT = a;
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("mage_action",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // mage_action ::= MAGIC_BARRIER 
            {
              Accion RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Accion a = (Accion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
        RESULT = a;
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("mage_action",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // mage_action ::= HEALING_RUNE 
            {
              Accion RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Accion a = (Accion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
        RESULT = a;
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("mage_action",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // mage_action ::= MEDITATE 
            {
              Accion RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Accion a = (Accion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
        RESULT = a;
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("mage_action",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // warrior_action ::= SLASH 
            {
              Accion RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Accion a = (Accion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
        RESULT = a;
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("warrior_action",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 70: // warrior_action ::= HEAVY_STRIKE 
            {
              Accion RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Accion a = (Accion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
        RESULT = a;
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("warrior_action",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 71: // warrior_action ::= SHIELD_BLOCK 
            {
              Accion RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Accion a = (Accion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
        RESULT = a;
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("warrior_action",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 72: // warrior_action ::= WAR_CRY 
            {
              Accion RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Accion a = (Accion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
        RESULT = a;
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("warrior_action",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 73: // warrior_action ::= REST 
            {
              Accion RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Accion a = (Accion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
        RESULT = a;
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("warrior_action",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 74: // any_action ::= mage_action 
            {
              Accion RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Accion a = (Accion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
        RESULT = a;
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("any_action",19, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 75: // any_action ::= warrior_action 
            {
              Accion RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Accion a = (Accion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
        RESULT = a;
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("any_action",19, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$Parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
              return CUP$Parser$do_action_part00000000(
                               CUP$Parser$act_num,
                               CUP$Parser$parser,
                               CUP$Parser$stack,
                               CUP$Parser$top);
    }
}

}
