
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int GT = 45;
  public static final int VICTORY_BONUS = 21;
  public static final int REST = 72;
  public static final int MAGE = 2;
  public static final int OPPONENT_RESOURCE = 33;
  public static final int SELF_HEALTH = 30;
  public static final int SHIELD_BLOCK = 70;
  public static final int ROUNDS = 14;
  public static final int COMMA = 59;
  public static final int OPPONENT_SCORE = 35;
  public static final int RBRACE = 53;
  public static final int RANDOM = 38;
  public static final int RPAREN = 57;
  public static final int HEALING_RUNE = 66;
  public static final int ARCANE_BOLT = 63;
  public static final int RUN = 6;
  public static final int HEAVY_STRIKE = 69;
  public static final int GET_MOVE = 39;
  public static final int LT = 46;
  public static final int LBRACE = 52;
  public static final int SELF_HISTORY = 36;
  public static final int LPAREN = 56;
  public static final int MAGE_COMBO_POINTS = 24;
  public static final int NOT = 51;
  public static final int MATCH = 4;
  public static final int FLOAT = 62;
  public static final int INITIAL = 8;
  public static final int THEN = 11;
  public static final int DAMAGE_POINT = 18;
  public static final int FIREBALL = 64;
  public static final int EQ = 43;
  public static final int GET_LAST_N_MOVES = 42;
  public static final int SEED = 17;
  public static final int SLASH = 68;
  public static final int WARRIOR_COMBO = 25;
  public static final int HEALING_POINT = 19;
  public static final int LAST_MOVE = 40;
  public static final int SCORING = 15;
  public static final int LOW_HEALTH_VICTORY = 27;
  public static final int ELSE = 12;
  public static final int INT = 61;
  public static final int ROUND_NUMBER = 28;
  public static final int LTE = 48;
  public static final int EOF = 0;
  public static final int MEDITATE = 67;
  public static final int PLAYERS = 13;
  public static final int MAIN = 5;
  public static final int OR = 50;
  public static final int RULES = 9;
  public static final int error = 1;
  public static final int MAGE_COMBO = 23;
  public static final int FAILED_ACTION_PENALTY = 22;
  public static final int GTE = 47;
  public static final int SELF_RESOURCE = 32;
  public static final int IF = 10;
  public static final int ID = 60;
  public static final int WARRIOR = 3;
  public static final int WARRIOR_COMBO_POINTS = 26;
  public static final int COLON = 58;
  public static final int WAR_CRY = 71;
  public static final int OPPONENT_HEALTH = 31;
  public static final int BONUSES = 16;
  public static final int RBRACKET = 55;
  public static final int GET_MOVES_COUNT = 41;
  public static final int MAGIC_BARRIER = 65;
  public static final int TOTAL_ROUNDS = 29;
  public static final int NEQ = 44;
  public static final int AND = 49;
  public static final int SUCCESSFUL_DEFENSE = 20;
  public static final int LBRACKET = 54;
  public static final int SELF_SCORE = 34;
  public static final int OPPONENT_HISTORY = 37;
  public static final int WITH = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MAGE",
  "WARRIOR",
  "MATCH",
  "MAIN",
  "RUN",
  "WITH",
  "INITIAL",
  "RULES",
  "IF",
  "THEN",
  "ELSE",
  "PLAYERS",
  "ROUNDS",
  "SCORING",
  "BONUSES",
  "SEED",
  "DAMAGE_POINT",
  "HEALING_POINT",
  "SUCCESSFUL_DEFENSE",
  "VICTORY_BONUS",
  "FAILED_ACTION_PENALTY",
  "MAGE_COMBO",
  "MAGE_COMBO_POINTS",
  "WARRIOR_COMBO",
  "WARRIOR_COMBO_POINTS",
  "LOW_HEALTH_VICTORY",
  "ROUND_NUMBER",
  "TOTAL_ROUNDS",
  "SELF_HEALTH",
  "OPPONENT_HEALTH",
  "SELF_RESOURCE",
  "OPPONENT_RESOURCE",
  "SELF_SCORE",
  "OPPONENT_SCORE",
  "SELF_HISTORY",
  "OPPONENT_HISTORY",
  "RANDOM",
  "GET_MOVE",
  "LAST_MOVE",
  "GET_MOVES_COUNT",
  "GET_LAST_N_MOVES",
  "EQ",
  "NEQ",
  "GT",
  "LT",
  "GTE",
  "LTE",
  "AND",
  "OR",
  "NOT",
  "LBRACE",
  "RBRACE",
  "LBRACKET",
  "RBRACKET",
  "LPAREN",
  "RPAREN",
  "COLON",
  "COMMA",
  "ID",
  "INT",
  "FLOAT",
  "ARCANE_BOLT",
  "FIREBALL",
  "MAGIC_BARRIER",
  "HEALING_RUNE",
  "MEDITATE",
  "SLASH",
  "HEAVY_STRIKE",
  "SHIELD_BLOCK",
  "WAR_CRY",
  "REST"
  };
}

